service: beeFit-backend
configValidationMode: error
frameworkVersion: '3'

useDotenv: true

custom:
  # profiles:
  #   dev: personal-aws
  stage: ${sls:stage}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npx prisma generate

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  # profile: ${self:custom.profiles.${sls:stage}}

# Lambda functions
functions:
  authHandler:
    handler: src/api/auth/index.handler
    timeout: 10
    events:
      - http:
          path: /api/auth/{proxy+}
          method: ANY
          cors:
            origins:
              - https://farmfresh.vercel.app
            allowCredentials: true
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}

  goalsHandler:
    handler: src/api/goals/index.handler
    timeout: 10
    events:
      - http:
          path: /api/goals/{proxy+}
          method: ANY
          cors:
            origins:
              - https://farmfresh.vercel.app
            allowCredentials: true
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}

# Serverless plugins
plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline
